services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:3476"
    depends_on:
      - app
    container_name: api-my-ssr-nginx11

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    container_name: api-my-ssr-app11

  mysql:
    image: mysql:8.3
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbBlogSsr
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8102:3306"
    container_name: api-my-ssr-db11

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    container_name: api-my-ssr-phpmyadmin11
