services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/public
    volumes:
      - ./:/var/www/public
    environment:
      - "DB_HOST=database"
      - "DB_PORT=3306"
    depends_on:
      - database
    networks:
      - api-ssr-network

  database:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbBlogSsr2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
     - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - api-ssr-network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - api-ssr-network

networks:
  api-ssr-network:
    driver: bridge
