services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - php
    container_name: api-my-ssr-nginx11
    networks:
      - api-ssr-network

  php:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - base
    container_name: php
    networks:
      - api-ssr-network
    expose:
      - "9000"

  base:
    image: mysql:8.3
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbBlogSsr2
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    container_name: api-my-ssr-db11
    networks:
      - api-ssr-network

networks:
  api-ssr-network:
    driver: bridge
