services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:3499"
    depends_on:
      - app
    container_name: api-my-ssr-nginx
    networks:
      - app-ssr-network

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: api-my-ssr-app
    environment:
      DB_HOST: db
    networks:
      - app-ssr-network

  db:
    image: mysql:8.3
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbBlogSsr
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: db
    ports:
      - "8101:3306"
    container_name: db
    networks:
      - app-ssr-network

networks:
  app-ssr-network:
    external: true
