services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:3499"
    depends_on:
      - app
    container_name: api-my-ssr-nginx
    networks:
      - api_lavrik_php_site

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: api-my-ssr-app
    environment:
      DB_HOST: db
    networks:
      - api_lavrik_php_site

  db:
    image: mysql:8.3
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbBlogSsr
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"
    container_name: api-my-ssr-db
    networks:
      - api_lavrik_php_site

networks:
  api_lavrik_php_site:
    name: api_lavrik_php_site
    driver: bridge
    external: true
