services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:3499"
    depends_on:
      - app
    container_name: api-my-ssr-nginx
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    container_name: api-my-ssr-app
    environment:
      DB_HOST: mysql
    networks:
      - my_network

  mysql:
    image: mysql:8.3
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbBlogSsr
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"
    container_name: api-my-ssr-db
    networks:
      - my_network

networks:
  network-my:
    driver: bridge
