services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:3499"
    depends_on:
      - app
    container_name: nginx-ssr-api
    networks:
      - api-ssr-network

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: app-ssr-api
    networks:
      - api-ssr-network

  db:
    image: mysql:8.3
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbBlogSsr
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"
    container_name: db-ssr-api
    networks:
      - api-ssr-network

networks:
  api-ssr-network:
    external: true
